### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#107]
Would be nice to have some automatic test checking here for each pull request :)

**Comment by helenst** [comment]
I've put in a .travis.yml and tested it on my own fork of the repo (https://travis-ci.org/helenst/djangogirls/builds) ... seems to work nicely - a little slow due to dependencies (psycopg, PIL etc) needing to be compiled each time. I can get it to cache the package downloads but not sure about the builds themselves!

I don't have the right permissions to switch on for the real repo so I'll leave that for somebody else to do. :sparkling_heart:

**Comment by aniav** [comment]
Done! Awesome work @helenst :)
