### ISSUE TITLE
make it possible to change the email of applicants

### ISSUE THREAD

**Issue by xrmx** [DjangoGirls/djangogirls#287]
We have a few applications with typos in the email field but we can't change them.

**Comment by burhan** [comment]
Can you explain exactly what is required here?

**Comment by KatuBeltz** [comment]
I'll work on that ticket today. :)

**Comment by bmispelon** [comment]
For anyone looking to work on this ticket, I think a solution/workaround might be to mark the `rsvp_yes_code` and `rsvp_no_code` fields as `editable=False` in the model definition (`Application` inside `applications/models.py`).

This would work because the two fields are the ones preventing someone from changing the email in the admin (they require a value but it's not clear what to put in them).

Using `editable=False` would make both fields disapear from the form in the admin, which is OK because their value is generated automatically later in the process.
