### ISSUE TITLE
Broken layout on mobile

### ISSUE THREAD

**Issue by wattawak** [DjangoGirls/djangogirls#306]
on https://djangogirls.org/denver/, there is a horizontal scroll and whitespace on the right-hand side of the screen when viewing the site on mobile

**Comment by wattawak** [comment]
@ludw you can see that we did set max-width:100% on the iframe for the map, but we're still having the issue

**Comment by ludw** [comment]
On what devices and browsers do you have this issue?

**Comment by wattawak** [comment]
iPhone 6s // Safari

**Comment by ludw** [comment]
Okay, I did some investigation and it looks like it's the word "programming" in the H1 at the top that get's to big. 

I think the best way to solve this is to add some css to the event page to make the text smaller on mobile devices. I'll see if I can get a patch for that merged since this seems to be an issue for pretty much all event pages. 

If you want a quick workaround you could try setting overflow-x: hidden on the surrounding div or something like that.
