### ISSUE TITLE
Add global install for django

### ISSUE THREAD

**Issue by amey-kudari** [DjangoGirls/djangogirls#501]
Id love to write how and update it, tell me if you guys want me to do it. Global install on linux is normally a better option acc me

**Comment by das-g** [comment]
What do you mean by "global install"?

Installing development dependencies with `sudo pip ...` into the **system site packages** is highly discouraged. Installing with `pip install --user` into the **user site packages** is fine for Python _applications_ the user wants to use as an end user. For _frameworks and libraries_ like Django, it's sub-optimal, because the user may work on several project requiring conflicting libraries or different versions of the same library. The same goes for installing through the **Linux distribution's package manager**: Good idea for end-user applications (and if available, probably even better than `--user`), but not really suitable for libraries you want to develop against. (Also because you might work on a project together with others, and not everyone's operating system may offer the same version of the library.)

That's why we teach how to use a Python virtual environment, so every project can have an isolated set of its own Python dependencies.
