### ISSUE TITLE
Add Sentry for error tracing to project

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#612]
Currently, troubleshooting errors on the website involves manually checking the error logs. However, sometimes when the server error occurs, there is no corresponding log on the error log on PythonAnywhere and we have to get the trace log by running `python manage.py shell` and run the piece of code we think broke the website to get a trace log of the error. Adding Sentry to the project could help us trace these failures better.

**Comment by marksweb** [comment]
Sentry makes every project better 😂 

Does the project make use of celery/redis/etc that could also be hooked up? I'm just getting familiar with the code, but could take a look at this.

**Comment by marksweb** [comment]
@amakarudze Sentry is already available in the settings if `SENTRY_DSN` is in the environment variables

https://github.com/DjangoGirls/djangogirls/blob/main/djangogirls/settings.py#L205

The version of sentry-sdk is quite old. It'd be good to upgrade that. Potentially adding pip-tools to the project would help with maintaining package versions that are compatible between one-another - though I don't believe there's any issues with the latest version of sentry-sdk because they only depend on `certifi` and `urllib3` & support `django>=1.8`

**Comment by amakarudze** [comment]
@ marksweb,

> Sentry makes every project better 😂
> 
> Does the project make use of celery/redis/etc that could also be hooked up? I'm just getting familiar with the code, but could take a look at this.

No, the project doesn't use celery/redis/etc. PythonAnywhere doesn't support celery yet.



> @amakarudze Sentry is already available in the settings if `SENTRY_DSN` is in the environment variables
> 
> https://github.com/DjangoGirls/djangogirls/blob/main/djangogirls/settings.py#L205
> 
> The version of sentry-sdk is quite old. It'd be good to upgrade that. Potentially adding pip-tools to the project would help with maintaining package versions that are compatible between one-another - though I don't believe there's any issues with the latest version of sentry-sdk because they only depend on `certifi` and `urllib3` & support `django>=1.8`

Thanks for that @marksweb. I have seen this before but we seem to have lost the credentials for the current setup. Couldn't use Sentry when we were fixing some issues a couple of weeks ago. Trying to see if we can recover them or start afresh, including upgrading the packages. Some details were lost during the transition from old to current trustees.

**Comment by marksweb** [comment]
@amakarudze Ah I see, so there's been a recent change in people with access. It'd be worth reaching out to those previously involved to see if they can access the sentry account. Even if it's empty, it saves a little setup.

I know I'm new to the project, but if you need any assistance, let me know. I've been using Sentry for some time and have experience with integration with build pipelines to include commit data & versioning so that you get some more detail to those issues.

**Comment by carltongibson** [comment]
Hey @marksweb — thanks for this. To fill you in, current status is "Yes, we want to use Sentry" — we just need to work out the account details (which includes asking if we can get a sponsorship from them on the account) — so it's more "admin"-blocked at the moment. Once we move that forward, your help in setting up the release integration and all that stuff will be much appreciated. 👍

**Comment by amakarudze** [comment]
Thanks @marksweb. Getting access details from old members may take more time than just starting afresh. I tried recovering the account but didn't get reset email so it may have been setup with someone's personal account. Like @carltongibson said, once we figure out the admin issues, we will definitely ask for your help setting up.

**Comment by amakarudze** [comment]
Hey @marksweb, we now have a sponsored account so we can work on this now. Yay!

**Comment by marksweb** [comment]
@amakarudze Fantastic news!!
