### ISSUE TITLE
Events map broken

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#855]
The map on https://djangogirls.org/en/events/map/ is now broken and only shows markers with no map. Inspecting the page indicates that the map no longer exists. It looks like the map has been deleted and needs to be created again so the page can work.

```
Request URL: https://a.tiles.mapbox.com/v4/olasitarska.m8nged0f.json?access_token=token&secure
Request Method: GET
Status Code: 410 Gone (from disk cache)
Remote Address: 52.85.219.178:443
Referrer Policy: same-origin
```

**Comment by jacklinke** [comment]
More details, including tips for transitioning to the new map styles at: https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4

**Comment by vanessa** [comment]
Do we have a screenshot of what this map looked like before, or can we just use a standard map?

**Comment by aniav** [comment]
The map wasn't anything custom, so we definitely could use something standard. I statted working on this but I also see someone else has been playing with it in the Studio on mapbox. I don't want to try and do the same thing.

I currently have the map itself loaded and I am working on making the events load onto the map because it was previously just a list of points where the new implementation of mapbox requires the points on the map to be prepared in a vector format as far as I could get in the docs?

Is someone further with the work on this or should I continue? 🙌

**Comment by amakarudze** [comment]
If you already have a PR ready to fix this @aniav  please submit it. Thanks for the help and your work on this.

Yes, Mapbox Studio API uses static data and it has taken me this long because I was trying to figure out how to use dynamic data which is also why I asked for your help on this.

Thanks again.

**Comment by aniav** [comment]
Yup, also sorry I didn't assign myself to this issue, it took me a few afternoons to go through Mapbox docs, they are sooo extensive 😅

**Comment by amakarudze** [comment]
No worries, yeah 🤣🤗 you tell me about the Mapbox docs. Took me days to go through them and go that far with Mapbox Studio. They're just extensive. 

I am away tomorrow but will definitely look at your PR over the weekend. Thanks for all your work on this.
